bnb48_index:
  name: bnb48_index
  port: 8888
  route_prefix: /bnb48_index
  bsc_rpc: ws://192.168.1.101:8545
  bsc_wrap_ca: 0x83b16A2C9Bf52Ea03036E8617c9Dd13AE975f218
  receive_fans_addr: 0x9567443394a3a611A6335Bab0e64f7F5E0cD83fd
  bulk_cannot_contain:
    - deploy
    - recap
    - mint

log:
  dir: /48club/logs
  level: debug
  max_size: 1000 #mb
  max_backups: 100
  max_age: 60 # days
  compress: false

mysql:
  url: root:mysqlpasswd@tcp(192.168.0.103:3306)/bnb48_inscription?charset=utf8mb4&parseTime=True&loc=Local
  prefix: ""
  max_idle_conns: 10
  max_open_conns: 50
  conn_max_lifetime: 60
  slow_threshold: 3
