bnb48_index:
  name: bnb48_index
  port: 8888
  route_prefix: /bnb48_index
  bsc_rpc: /opt/.ethereum/geth.ipc

log:
  dir: /app/logs
  level: debug
  max_size: 1000 #mb
  max_backups: 100
  max_age: 60 # days
  compress: false

mysql:
  url: root:mysqlpasswd@tcp(mysql:3306)/bnb48_inscription?charset=utf8mb4&parseTime=True&loc=Local
  prefix: ""
  max_idle_conns: 10
  max_open_conns: 50
  conn_max_lifetime: 60
  slow_threshold: 3
