bnb48_index:
  name: bnb48_index
  port: 8888
  route_prefix: /bnb48_index
  bsc_rpc: /opt/.ethereum/geth.ipc
  bsc_wrap_ca: 0x6D81f3049F7b79951551cF3E2AA8D409f9303c69
  bulk_cannot_contain:
    - deploy
    - recap
    - mint

log:
  dir: /48club/logs
  level: debug
  max_size: 1000 #mb
  max_backups: 100
  max_age: 60 # days
  compress: false

mysql:
  url: root:mysqlpasswd@tcp(mysql:3306)/bnb48_inscription?charset=utf8mb4&parseTime=True&loc=Local
  prefix: ""
  max_idle_conns: 10
  max_open_conns: 50
  conn_max_lifetime: 60
  slow_threshold: 3
